### ISSUE TITLE
Refresh controlled vocabulary of "reproducción" class

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#11]
Three options were eliminated, please refresh the controlled vocabulary

![image](https://cloud.githubusercontent.com/assets/7827998/11073299/00e6ba28-87b8-11e5-9415-96e374b8ed26.png)

**Comment by mcubillos** [comment]
Fixed in 9013a13afaefec3a367d2cea1da3bc34b4637ce2
