### ISSUE TITLE
Add a sentence in the information icon of "Amenazas directas" class

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#17]
In the information icon include after the class definition the following sentence: "Vocabulario controlado de acuerdo al esquema de clasificación de amenazas (versión 3.2) de IUCN"

![image](https://cloud.githubusercontent.com/assets/7827998/11094243/931e7d32-885c-11e5-84af-8d75fdaf9d13.png)

**Comment by mcubillos** [comment]
Fixed in 9013a13afaefec3a367d2cea1da3bc34b4637ce2
