### ISSUE TITLE
Add an information icon for "tipos de acciones" element

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#19]
Add an information icon for "Tipos de acciones" with the following sentence: "Vocabulario controlado de acuerdo al esquema de clasificación de acciones de conservación (versión 2.0) de IUCN"

![image](https://cloud.githubusercontent.com/assets/7827998/11094705/2c2465ee-885f-11e5-8710-35a9908f05d0.png)

**Comment by mcubillos** [comment]
Fixed in 9013a13afaefec3a367d2cea1da3bc34b4637ce2
