### ISSUE TITLE
Change select box name in the "Distribución atomizada" element <"Distribución" class>

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#21]
Change select box name from "Código del país" to "País" in the "Distribución atomizada" element

![image](https://cloud.githubusercontent.com/assets/7827998/11097028/062df786-886b-11e5-9e9b-3a3589a83671.png)

**Comment by mcubillos** [comment]
Changed in 9013a13afaefec3a367d2cea1da3bc34b4637ce2
