### ISSUE TITLE
Text of information icon duplicate

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#23]
The text of the information icon is the same for "Reclutamiento" and "Tasa de crecimiento", the text of "Reclutamiento" must be:

English: Proportion of plants or animals that reach a size or age when they become less vulnerable to a change in their environment. Stage in which plants or animals can be consumed and can survive, as well as reproduce.

Spanish: Proporción de plantas o animales que alcanzan un tamaño o edad en la que se hacen menos vulnerables a un cambio en su entorno. Etapa en la cual las plantas o animales pueden ser consumidos y pueden sobrevivir, así como reproducirse.

![image](https://cloud.githubusercontent.com/assets/7827998/11101421/c9ac8c04-8884-11e5-9a46-89acd405e879.png)

**Comment by mcubillos** [comment]
Fixed in 9013a13afaefec3a367d2cea1da3bc34b4637ce2
