### ISSUE TITLE
 Text of information icon duplicate #2

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#24]
The text of the information icon is the same for "Descripción etapas de vida" and "Proporción de individuos por etapa", the text of "Descripción etapas de vida" must be:

English: Sex/age categories or life stages of a species; can be size in the case of plants.

Spanish: Categorías de sexo/edad o etapas de vida de una especie; puede ser de tamaño en el caso de plantas.

![image](https://cloud.githubusercontent.com/assets/7827998/11101714/8986401e-8886-11e5-9802-ae57ed409bb7.png)

**Comment by mcubillos** [comment]
Fixed in 9013a13afaefec3a367d2cea1da3bc34b4637ce2
