### ISSUE TITLE
Error in text of  information icon "Sinónimos atomizados"

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#25]
The text have the definition of "SynonymsUnstructured"

![image](https://cloud.githubusercontent.com/assets/7827998/11129738/0538cf60-894f-11e5-87ec-154adf2d5d39.png)

**Comment by mardeles** [comment]
Definition in english: "Different names for this taxon"

**Comment by mcubillos** [comment]
Fixed in 9013a13afaefec3a367d2cea1da3bc34b4637ce2
