### ISSUE TITLE
Error in visualization of the "sección anterior" and "sección siguiente" buttons

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#27]
The buttons "sección anterior" and "sección siguiente" at first sight unseen and only visibles when the cursor is on it

![image](https://cloud.githubusercontent.com/assets/7827998/11150725/78ff7bda-89f7-11e5-8f9a-6e3af9337150.png)

**Comment by mcubillos** [comment]
Fixed in b2fa1d9acd52adab921c0448b362429cdf797de6
