### ISSUE TITLE
¿The select box of "Distancia" element <Dispersion class> will fill with a controlled vocabulary of measures (m, cm, mm etc.)? if so, the options are missing

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#31]
![image](https://cloud.githubusercontent.com/assets/7827998/11156603/dbef16ce-8a1a-11e5-95c0-7d437c6adfa2.png)

**Comment by mcubillos** [comment]
Fixed in b2fa1d9acd52adab921c0448b362429cdf797de6
