### ISSUE TITLE
There aren't enables fields for documenting the elements "Estatus legal de protección", "Estatus", "Tipo" y "Norma" <Marco Normativo class>

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#33]
Please leave the elements "Estatus legal de protección", "Estatus", "Tipo" y "Norma" as a field to document text like the element "Nombre de la norma"

![image](https://cloud.githubusercontent.com/assets/7827998/11214075/50c7e79c-8d0d-11e5-8a3d-6d650f330c16.png)

**Comment by mcubillos** [comment]
Fixed in b2fa1d9acd52adab921c0448b362429cdf797de6
