### ISSUE TITLE
Remove the second drop down list in "Condiciones ambientales" class

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#36]
Remove the second drop-down list box and include a field for documenting numerical data

![image](https://cloud.githubusercontent.com/assets/7827998/11251399/11dda614-8dff-11e5-861c-b4ec799583cd.png)

**Comment by mcubillos** [comment]
Fixed in b2fa1d9acd52adab921c0448b362429cdf797de6
