### ISSUE TITLE
Change the format date when saving the element "cobertura temporal" <"Distribución" class>

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#40]
The format date should be only "AAAA-MM-DD", for example, in the image should be: 

2015-10-28/2015-11-27

![image](https://cloud.githubusercontent.com/assets/7827998/11378620/166454a2-92ba-11e5-9689-b348b3d8b700.png)

**Comment by mcubillos** [comment]
Fixed in ef87c472af48d54149a41ab4fd0228504fddcbe8
