### ISSUE TITLE
Change "Tipo" for "Descripción tipo de acciones" and put it below the element "Tipo de acciones" as a field to document text <Manejo y conservación class>

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#41]
![image](https://cloud.githubusercontent.com/assets/7827998/11426410/18e080fe-942a-11e5-87a0-09747e042a89.png)

**Comment by mcubillos** [comment]
Fixed in 2c0b6eb2a13a7512206b4066629e0cdf8bcdbb45
