### ISSUE TITLE
Include a text in the information icon before the definition of Invasividad "According to GSIN ..."

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#43]
According to GSIN "the information about invasive ........"

![image](https://cloud.githubusercontent.com/assets/7827998/11430425/906d9416-9454-11e5-91bf-91084e9bc6cb.png)

**Comment by mcubillos** [comment]
Fixed in e29a61dc564ed1edef40cfe82afc94cba0b0bb70
