### ISSUE TITLE
Remove options of drop-down list "aplica para" in the "estado de amenaza" class

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#5]
Only set the options "Colombia" and "Global" in the select box "Aplica para" 

![image](https://cloud.githubusercontent.com/assets/7827998/11068147/ffb33e84-879d-11e5-9449-e392fdd64e8e.png)

**Comment by mcubillos** [comment]
Fixed in 9013a13afaefec3a367d2cea1da3bc34b4637ce2
