### ISSUE TITLE
Element "Nombres comunes"

### ISSUE THREAD

**Issue by ghost** [SIB-Colombia/mamut#52]
- This element should not have the field of references or it has to be hidden.
-  This element should have the field of _Proveedor de contenidos_
- The "Add button" have problems with the visualization. When you add another name It turns in a "minus" symbol not in a "plus" symbol. 
- Is neccesary that the field "Idioma" have an additional Normal string field to put indigenous languages (huitoto, wayúu)

**Comment by mcubillos** [comment]
Fixed in 89849b4ca4ad82e5e4d8cb2e3ed25d8b9e8d9307 but the problem with the add button is present yet
