### ISSUE TITLE
New atribute on AncilliaryDataClass

### ISSUE THREAD

**Issue by ghost** [SIB-Colombia/mamut#54]
Is neccesary that in "Información Adicional" section, the atribute [_additionalInformation_](https://github.com/PlinianCore/Documentation/wiki/AncillaryDataClass#additionalinformation) of PlinianCore Standard be agregate. The name of this element in spanish will be "Otros recursos"; is a NormalString Class

**Comment by mcubillos** [comment]
Fixed in 89849b4ca4ad82e5e4d8cb2e3ed25d8b9e8d9307
