### ISSUE TITLE
Element "Sinónimos atomizados"

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/mamut#55]
When clicking "Add a new synonym" there is no space to complete the nomenclaturakStatus (Estado nomenclatural"

![image](https://cloud.githubusercontent.com/assets/13892476/13052296/0c0fd85c-d3cc-11e5-8e87-dcdf90e59331.png)

**Comment by mcubillos** [comment]
Fixed in 89849b4ca4ad82e5e4d8cb2e3ed25d8b9e8d9307
