### ISSUE TITLE
Select all the "Departments" at once

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/mamut#60]
In order to optimize the time of the users. We have to have the option "Todos"

**Comment by mcubillos** [comment]
Fixed in 89849b4ca4ad82e5e4d8cb2e3ed25d8b9e8d9307

**Comment by vdean26** [comment]
We need to be able to edit the entries in order to add "municipios" to the selection.

**Comment by mcubillos** [comment]
Now you can edit the entries in order to add 'municipios'. This change was made in f97faffb2847ef2203ece08229d2e20ff8def414
