### ISSUE TITLE
Element "Distribución" summary table on edit mode

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/mamut#62]
Accentuate the difference between the information that is available for editing and the summary table of the results.

![image](https://cloud.githubusercontent.com/assets/13892476/13082536/14508fc4-d49f-11e5-9ea9-56ba35b4b17c.png)

**Comment by mcubillos** [comment]
Fixed in 89849b4ca4ad82e5e4d8cb2e3ed25d8b9e8d9307
