### ISSUE TITLE
"Agregar nueva referencia" Menu scroll up/down

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/mamut#64]
When the window is not big enough, it is not possible to close the "Agregar nueva referencia menu" we need a scroll up/down that allows the navigation in the menu and a close button at the top.

![image](https://cloud.githubusercontent.com/assets/13892476/13090835/092fc2d2-d4c6-11e5-8544-66bf92b3b561.png)

**Comment by mcubillos** [comment]
Fixed in 8d50e162ab03e98f772ab2c685a18dba18fda104
