### ISSUE TITLE
Add a placeholder and a title to Scientific name 

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/mamut#65]
Add a placeholder in the blank box " Ingresar nombre científico" and as the title use "Nombre del Taxón"

![image](https://cloud.githubusercontent.com/assets/13892476/13091367/bd56100c-d4c8-11e5-9a98-1be0ad23f60a.png)

**Comment by mcubillos** [comment]
Fixed in 8d50e162ab03e98f772ab2c685a18dba18fda104
