### ISSUE TITLE
Please add a help message when standing on each section

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/mamut#88]
Please add a help message when standing on each section showing the content of Terms included in the section. Please follow the indications in this document. 

https://docs.google.com/a/humboldt.org.co/spreadsheets/d/1kOFcZw4LURHrZRNUA2CGPdBJPIPfj2JQYmbKQNWoZ14/edit?usp=sharing

**Comment by mcubillos** [comment]
Fixed in a14c9ea5edf2ecc409fca1414ba3cfec39ce9ab8
