### ISSUE TITLE
Remove the controlled vocabulary in "Ciclo de vida" class

### ISSUE THREAD

**Issue by mardeles** [SIB-Colombia/mamut#9]
Remove the controlled vocabulary in "Ciclo de vida" class and just leave the unstructured field 

![image](https://cloud.githubusercontent.com/assets/7827998/11071368/95f679dc-87ae-11e5-8631-1c175604c5f3.png)

**Comment by mcubillos** [comment]
Fixed in 9013a13afaefec3a367d2cea1da3bc34b4637ce2
