### ISSUE TITLE
EnvironmentalEnvelope

### ISSUE THREAD

**Issue by ghost** [SIB-Colombia/mamut#93]
This element must show the **measurementUnit** (can found in [Lenguajes controlados](https://docs.google.com/a/humboldt.org.co/spreadsheets/d/1gd0bxeGaYiXuCK9wm1uJAOXHj1cOiKEzTViMvGfvXJA/edit?usp=sharing) document) related with each **measurmentType**. The **measurementValue** should be a "String". Example:

Temperatura ambiente     | 23- 24 |          Grados centígrados (°C)

**Comment by mcubillos** [comment]
Fixed in 05746a7ac0fdcddec4391fe7589a947edae816f
