### ISSUE TITLE
Delete duplicates

### ISSUE THREAD

**Issue by ghost** [SIB-Colombia/mamut#97]
Please eliminate from the editor the taxon pages duplicate marked with an "X" in [this file](https://docs.google.com/spreadsheets/d/1tASAvKlgxTQ3YkjHmu7QXASxS6yc8FpZIjsbbKERCLA/edit?usp=sharing).

**Comment by mcubillos** [comment]
- [x] 56c94a46f0106c67230e743e
- [x] 56ccf215207ecea54a561e57
- [x] 56ca99c7f0106c67230e746a
- [x] 56c80090f0106c67230e7426
- [x] 56c7f29af0106c67230e7421
- [x] 56c55876f0106c67230e73a1
- [x] 56c3f3c3f0106c67230e736d
- [x] 56c3f3c2f0106c67230e736c
- [x] 56c3f3c2f0106c67230e736b
- [x] 56c3f35bf0106c67230e7369
- [x] 56c2a6d9f0106c67230e7336
- [x] 56c16024f0106c67230e7316
- [x] 56c15ec4f0106c67230e7315
- [x] 56d4af573c16479905cba8a6
- [x] 56d4af573c16479905cba8a7
- [x] 56d4af573c16479905cba8a8
- [x] 56d4af573c16479905cba8a9

**Comment by andresciceri** [comment]
The elements was deleted.
