### ISSUE TITLE
Remove locationStandard element from section Invasividad

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/mamut#98]
browser:chrome

The element locationStandard is lacking a useful vocabulary that applies to Colombia. 

https://docs.google.com/spreadsheets/d/1gd0bxeGaYiXuCK9wm1uJAOXHj1cOiKEzTViMvGfvXJA/edit#gid=222474905

**Comment by mcubillos** [comment]
Fixed in 123444ff6c6adc17fa143d5b3dfd0b49d00b6563
